Features/#1944 key
logipro-fr/SocialNetworksPublisher pull request #10
Opened 2024-08-26 08:31 UTC by ApoPedro

2024-08-26 08:32 UTC, ApoPedro commented
Vérifier classe abstraite AbstractKeyData, avec TwitterKeyData et LinkedInData.

2024-08-27 10:42 UTC, frederic100 requested changes
[WARN] message d'exception
[ERR] domain class Identity $value
[WARN] annotation phpstan a eviter

2024-08-27 10:42 UTC, frederic100 commented on src/Domain/Model/Key/Key.php
> +        $this->value = new Identity(new PageId("null"));
Il me semble qu'une clef sans page n'a pas de sens => ne devrait elle pas  etre initialisée dans le consctructeur avec une vrai valeur et pas de setIdentity (imuable)
(et aussi c'est dommage d'avoir ici la dépence à PageId)

2024-08-27 10:42 UTC, frederic100 commented on src/Infrastructure/Persistence/Doctrine/Types/KeyDataType.php
> +            throw new SocialNetworksDoesntExist("");
un message (testé) serait bienvenu

2024-08-27 10:42 UTC, frederic100 commented on src/Domain/Model/Key/TwitterKeyData.php
> +            throw new KeyDataEmptyBearerTokenException();
des messages dans les exceptions aident en prod

2024-08-27 10:42 UTC, frederic100 commented on src/Infrastructure/Api/V1/AddPageController.php
> +            $this->em->flush();
le mecanisme de distribution des Event n'a pas l'air d'etre mis en place

2024-08-27 10:42 UTC, frederic100 commented on src/Infrastructure/Api/V1/CreateKeyController.php
> +            $this->em->flush();
mecanisme de distribution des events semble absent

2024-08-27 10:42 UTC, frederic100 commented on src/Infrastructure/Api/V1/AddPageController.php
> +        $content = $request->getContent();
str_val plutot que phpstan
(en general : eviter commentaire phpstan autant que possible)

2024-08-27 12:33 UTC, ApoPedro commented on src/Domain/Model/Key/TwitterKeyData.php
> +            throw new KeyDataEmptyBearerTokenException();
Les messages et les codes sont des constantes dans ma classe exceptions et sont automatiquement appélés lorsque l'erreur est construise.

2024-08-27 13:29 UTC, frederic100 approved these changes

2024-08-27 13:30 UTC, merged