Publish on twitter
logipro-fr/SocialNetworksPublisher pull request #6
Opened 2024-07-04 07:26 UTC by ApoPedro

2024-07-08 05:54 UTC, frederic100 requested changes

2024-07-08 05:54 UTC, frederic100 commented on .gitignore
> +src/public/log/exceptions.log
[ERR] securité ce fichier ne devrait  pas etre exposé en http

2024-07-08 05:54 UTC, frederic100 commented on phpunit.xml.dist
> +    <env name="TWITTER_REFRESH_TOKEN" value="azerty"/>
[notice] des noms plus long et significatif pour les clef peuvent aider  ex: "TwitterIdForTestPurpose" plutot que "test"

2024-07-08 05:54 UTC, frederic100 commented on src/Domain/Model/Post/SocialNetworks.php
>      public static function fromString(string $value): self
[Warn] il semble qu'il existe déjà la function from pour faire cette conversion ?

2024-07-08 05:54 UTC, frederic100 commented on src/Infrastructure/Provider/Exceptions/BadRequestException.php
> +    public const ERROR_CODE = 400;
[notice] comme on est dans l'infra, on peut s'appuyer sur les constante de l'objet HttpResponse (je crois ) qui est porteur des valeurs sur des cosntantes  avec des noms significatifs

2024-07-08 05:54 UTC, frederic100 commented on src/Infrastructure/Provider/Twitter/TwitterBearerToken.php
> +    public const BEARER_PATH = "/var/BearerToken.txt";
[notice] Les 3 fichiers pourraient se trouver dans un sous dossier var/TwitterBearerToken

2024-07-08 05:54 UTC, frederic100 commented on tests/unit/Infrastructure/Provider/Twitter/TwitterBearerTokenTest.php
> +        $sut = new TwitterBearerToken(
[refacto] des fois une bonne methode fabrique...

2024-07-08 05:54 UTC, frederic100 commented on tests/unit/Infrastructure/Provider/Twitter/TwitterClientTest.php
> +    public function testTwitterRequest(): void
[notice] precisiion dans le nom. L'intention de faire une request : OK mais pour quoi ?

2024-07-08 05:54 UTC, frederic100 commented on tests/unit/Infrastructure/Provider/Twitter/TwitterClientTest.php
> +        $twitterResponse2 = [
[refacto] function trop longue. Peut etre faire une fonction spécifiquement pour initialiser le mécanisme http

2024-07-08 05:54 UTC, frederic100 commented on tests/unit/ressources/TwitterBadRequestResponse.json
> +    "error_description": "Value passed for the token was invalid."
[notice] peut etre un indice concernant la valeur erronné du token (les caractere de debut + ceux de fin, ex: "Ab1...2e3"

2024-08-05 08:42 UTC, Boubounech commented on phpunit.xml.dist
> +    <env name="TWITTER_REFRESH_TOKEN" value="azerty"/>
Je suis obligé de mettre les même noms que ceux situés dans ma classe TwitterBearerToken.php pour que les tests unitaires fonctionnent.

2024-08-05 08:58 UTC, ApoPedro commented on src/Domain/Model/Post/SocialNetworks.php
>      public static function fromString(string $value): self
ça me permet de pouvoir Throw une exception si jamais l'utilisateur ne fournit pas de Social Networks ou qu'il en fournisse un qui n'est pas gérer.

2024-08-05 09:42 UTC, ApoPedro commented on tests/unit/ressources/TwitterBadRequestResponse.json
> +    "error_description": "Value passed for the token was invalid."
J'ai récupérer ces valeurs de l'API de twitter qui nous fournit pas les caractères.

2024-08-06 14:28 UTC, merged